#!/bin/bash
qeth_configure -l 0.0.1000 0.0.1001 0.0.1002 1
echo "0.0.1000,0.0.1001,0.0.1002 #`date`" >>/boot/zipl/active_devices.txt

sleep 2
cio_ignore -R
znetconf -R -n
sleep 2
rm -f /etc/sysconfig/network//ifroute-eth*
sed -i '/^\s*NETCONFIG_DNS_STATIC_SERVERS="/d' /etc/sysconfig/network/config
udevadm trigger
udevadm settle
sleep 2
znetconf -A
cio_ignore -u
wicked ifreload all
rm -rf /tmp/znetconfig.sh
